# Generated by Django 4.2.2 on 2023-06-29 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studybuddy_app', '0002_alter_meetup_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
