# Generated by Django 4.2.2 on 2023-07-02 08:04

import datetime
from django.db import migrations, models
import studybuddy_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy_app', '0003_meetup_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='end_time',
        ),
        migrations.AddField(
            model_name='meetup',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='start_time',
            field=studybuddy_app.models.ConvertingDateTimeField(default=studybuddy_app.models.tomorrow, verbose_name='start time'),
        ),
    ]
